/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CtcDecoderRouteImport } from './routes/ctc-decoder'
import { Route as SalaryExplorerRouteImport } from './routes/salary-explorer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CtcDecoderRoute = CtcDecoderRouteImport.update({
  id: '/ctc-decoder',
  path: '/ctc-decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryExplorerRoute = SalaryExplorerRouteImport.update({
  id: '/salary-explorer',
  path: '/salary-explorer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ctc-decoder': typeof CtcDecoderRoute
  '/salary-explorer': typeof SalaryExplorerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ctc-decoder': typeof CtcDecoderRoute
  '/salary-explorer': typeof SalaryExplorerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ctc-decoder': typeof CtcDecoderRoute
  '/salary-explorer': typeof SalaryExplorerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ctc-decoder' | '/salary-explorer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ctc-decoder' | '/salary-explorer'
  id: '__root__' | '/' | '/ctc-decoder' | '/salary-explorer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CtcDecoderRoute: typeof CtcDecoderRoute
  SalaryExplorerRoute: typeof SalaryExplorerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ctc-decoder': {
      id: '/ctc-decoder'
      path: '/ctc-decoder'
      fullPath: '/ctc-decoder'
      preLoaderRoute: typeof CtcDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-explorer': {
      id: '/salary-explorer'
      path: '/salary-explorer'
      fullPath: '/salary-explorer'
      preLoaderRoute: typeof SalaryExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CtcDecoderRoute: CtcDecoderRoute,
  SalaryExplorerRoute: SalaryExplorerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
