/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CtcDecoderRouteImport } from './routes/ctc-decoder'
import { Route as LayoffRadarRouteImport } from './routes/layoff-radar'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SalaryExplorerRouteImport } from './routes/salary-explorer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AnalysisSlugRouteImport } from './routes/analysis.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CtcDecoderRoute = CtcDecoderRouteImport.update({
  id: '/ctc-decoder',
  path: '/ctc-decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoffRadarRoute = LayoffRadarRouteImport.update({
  id: '/layoff-radar',
  path: '/layoff-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryExplorerRoute = SalaryExplorerRouteImport.update({
  id: '/salary-explorer',
  path: '/salary-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisSlugRoute = AnalysisSlugRouteImport.update({
  id: '/analysis/$slug',
  path: '/analysis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ctc-decoder': typeof CtcDecoderRoute
  '/layoff-radar': typeof LayoffRadarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salary-explorer': typeof SalaryExplorerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ctc-decoder': typeof CtcDecoderRoute
  '/layoff-radar': typeof LayoffRadarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salary-explorer': typeof SalaryExplorerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/analysis': typeof AnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/ctc-decoder': typeof CtcDecoderRoute
  '/layoff-radar': typeof LayoffRadarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salary-explorer': typeof SalaryExplorerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ctc-decoder'
    | '/layoff-radar'
    | '/reset-password'
    | '/salary-explorer'
    | '/dashboard'
    | '/submit'
    | '/analysis/$slug'
    | '/analysis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ctc-decoder'
    | '/layoff-radar'
    | '/reset-password'
    | '/salary-explorer'
    | '/dashboard'
    | '/submit'
    | '/analysis/$slug'
    | '/analysis'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ctc-decoder'
    | '/layoff-radar'
    | '/reset-password'
    | '/salary-explorer'
    | '/_authenticated/dashboard'
    | '/_authenticated/submit'
    | '/analysis/$slug'
    | '/analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CtcDecoderRoute: typeof CtcDecoderRoute
  LayoffRadarRoute: typeof LayoffRadarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalaryExplorerRoute: typeof SalaryExplorerRoute
  AnalysisSlugRoute: typeof AnalysisSlugRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ctc-decoder': {
      id: '/ctc-decoder'
      path: '/ctc-decoder'
      fullPath: '/ctc-decoder'
      preLoaderRoute: typeof CtcDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layoff-radar': {
      id: '/layoff-radar'
      path: '/layoff-radar'
      fullPath: '/layoff-radar'
      preLoaderRoute: typeof LayoffRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-explorer': {
      id: '/salary-explorer'
      path: '/salary-explorer'
      fullPath: '/salary-explorer'
      preLoaderRoute: typeof SalaryExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$slug': {
      id: '/analysis/$slug'
      path: '/analysis/$slug'
      fullPath: '/analysis/$slug'
      preLoaderRoute: typeof AnalysisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CtcDecoderRoute: CtcDecoderRoute,
  LayoffRadarRoute: LayoffRadarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalaryExplorerRoute: SalaryExplorerRoute,
  AnalysisSlugRoute: AnalysisSlugRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
